name: AVisualizer

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: login heroku
        env: 
          HEROKU_API_KEY:${{secrets.HEROKU_API_KEY}}
        run: heroku container:login
      - name: Build with Maven and Push
        env:
          HEROKU_API_KEY:${{secrets.HEROKU_API_KEY}}
        run: |
            mvn clean package
            cd avisualizer-back/
            heroku plugins:install java
            heroku deploy:jar target/avisualizer-back.jar --app avisualizer
