name: AVisualizer

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          heroku_api_key: ${{secrets.HEROKU_API_SECRET}}
          heroku_app_name: "avisualizer"
      - name: Build with Maven
        run: |
            mvn clean package
            cd avisualizer-back/
            heroku deploy:jar target/avisualizer-back.jar --app avisualizer
